function GRINcalculation = calculateGRIN(ideltas,z,n1,n2,grinprofile,...
    discretization,shapeparameters,qty,spacings,offcenter,liftdistance,...
    liftspeed,retractspeed,holdtime,numbersoflayerexposures,refresh,zinterval)

[filename,savetopath] = uiputfile('*.mat',...
    'Save calculation results to:');

%% Starting variables
% formulation and printer
f = load('BisEMA.mat','BisEMA');
formulation = f.BisEMA;

printer = printerinfo('MonoPrinter1-246');

load('startingparameters.mat','itaus','igsvs');

%% GRIN
[baseimages,refractiveindices,~] = isoimages...
   (n1,n2,grinprofile,shapeparameters,discretization,printer.pixelSize);


%% convert indexmatrix to conversionmatrix
indexmatrix = ones(z*1000/zinterval,1)*refractiveindices';
conversionmatrix = convertindexmatrix(formulation, indexmatrix);

%% Calculating printing parameters
t1 = tic;

calculations = calculateprintparameters(formulation, printer, ...
                        conversionmatrix, ideltas, itaus, igsvs, ...
                        numbersoflayerexposures,refresh, zinterval);

toc(t1)

%% summarize and save
GRIN = struct('profile',grinprofile,'n1',n1,'n2',n2,...
    'shapeParameters',shapeparameters,'discretization',discretization,...
    'refractiveIndices',refractiveindices,'baseImages',baseimages); 

printconfiguration = struct('locationInfo',struct('quantity',qty,...
            'spacings',spacings,'offcenter',offcenter,...
            'units',struct('spacing','mm','offcenter','mm')),...
            'interlayerParameters',struct(...
            'liftDistance', liftdistance,'liftSpeed', liftspeed,...
            'retractSpeed',retractspeed,'holdTime', holdtime,...
            'units', struct('liftDistance', 'mm', ...
            'speed', 'mm/s', 'holdTime', 'second')));

GRINcalculation = struct('formulation',formulation,'printer',printer,...
    'GRIN',GRIN,'calculations',struct('refresh',calculations.refresh,...
    'targetConversionMatrix',calculations.targetConversionMatrix,...
    'predictions',calculations.predictions,'units',calculations.units),...
    'printConfiguration',printconfiguration);

save([savetopath filename],'GRINcalculation');

%% create files for printing
recreatemonoimagesandbuildscript(GRINcalculation, savetopath);